### ISSUE TITLE
Inefficient image log

### ISSUE THREAD

**Issue by melisandeteng** [cc-ai/MaskGenerator#14]
Regarding the comet image log: 
It seems that we are loading _number of images to display_ * _batch size_ and only displaying the first image of each batch loaded. And we only want to display _number of images to display_.
Does it make sense to change the code  to load the images in this way: 
`test_display_images =[Dict(val_loader.dataset[i]) for i in range(opts.comet.display_size)] `
rather than: 
`test_display_images = [Dict(iter(val_loader).next()) for i in range(opts.comet.display_size)]`
It seems to me that would be more efficient. 
If you agree I'll make changes and PR!

**Comment by vict0rsch** [comment]
I agree it would make sense ; also I think displaying a max of 5x5 grid of images would make things clearer

**Comment by melisandeteng** [comment]
See [this commit](https://github.com/cc-ai/MaskGenerator/commit/6e1fed6a63859c134a7bb2323d57c8e0c624f9e0 )

Changed the way display images are loaded, but there is an issue with the logging of the imaged from the simulated world: the same image is displayed repeatedly in an image grid. 
Can you help @vict0rsch @51N84D  ?

**Comment by melisandeteng** [comment]
There was actually no issue in repeated images, it is just that the dataset on which the images were tested  had repeating images. 
We take the first images of a batch, so if we are in the situation where a lot of consecutive images are similar, we will get visualizations of similar images.

**Comment by melisandeteng** [comment]
@vict0rsch  I added an option in the config file to choose a set on indexes

**Comment by vict0rsch** [comment]
I saw that in #20 thanks!
